version: '3'
services:
    scraper:
        build: .
        container_name: scraper
        command: npm start
        volumes:
            - .:/usr/app
            - /usr/app/node_modules
        ports:
            - "3000:3000"
        depends_on:
            - mysql
        environment:
            DATABASE_URL: "mysql://scraper:scraper12345@mysql/scrapes"
    mysql:
        image: mysql
        container_name: scraper_db
        environment:
            MYSQL_DATABASE: scrapes
            MYSQL_USER: scraper
            MYSQL_PASSWORD: scraper12345
