version: '3'
services:
    scraper:
        build: .
        container_name: scraper
        command: npm start
        volumes:
            - ./src:/usr/app/src
        ports:
            - "3000:3000"
        depends_on:
            - mongo
        environment:
            DATABASE_URL: "mongodb://scraper_db:27017/"
    mongo:
        image: mongo
        container_name: scraper_db
